### PR TITLE
simplify test scripts

### PR DESCRIPTION
**Pull request by PeterDaveHello**
I think we don't need a additional shell script to do the test.

### CODE REVIEW

**Comment by kaelzhang** [comment]
Then we need to `npm install -g mocha` to run the test. I'd like to declare all dev dependencies explicitly.

**Comment by PeterDaveHello** [comment]
No we don't, as you can see, it passed the test on travis-ci, and also on my computer.

**Comment by kaelzhang** [comment]
Because travis-ci has preinstalled mocha into the base layer of its docker layer and you've also have mocha installed. But others who do not use mocha will fail the test, it is much better to declare dev dependencies explicitly～

Thanks all the same :)

**Comment by PeterDaveHello** [comment]
hmmm .,, did I miss something? There is no mocha in my system I think, I only install it by `npm install` in the repo.

**Comment by kaelzhang** [comment]
You're right. Ok, fine. 

`npm` does this for us by adding `node_modules/mocha/.bin` to the working directory of the child process. See [here](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L80)

**Pull request merged**
